version: '3'
services:
  dw:
    container_name: postgres
    build: ./docker/postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=ad_events
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  dl:
    container_name: python_data_loader
    restart: "no"
    build: ./data_loader

